name: Playwright Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov
    - name: Install Playwright browsers
      run: playwright install
    - name: Run tests with coverage
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: pytest tests/ --cov=./ --cov-report=xml --junitxml=test-results/results.xml -p pytest_asyncio
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results/results.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Count tests
      run: echo "TEST_COUNT=$(pytest tests/ --collect-only -q | wc -l)" >> $GITHUB_ENV
    - name: Create custom badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: d805d5fbdf53940d8e82e9891f249ca2
          filename: test-count.json
          label: tests
        message: ${{ env.TEST_COUNT }}
        color: green  
